name: Docs Deploy

on:
  push:
    branches: [ master ]
    paths:
      - "src/components/*"
      - "src/components/specimens/*"
      - "src/main.js"
      - "package.json"

jobs:
  docs_deploy:
    runs-on: ubuntu-latest

    name: 'Docs Deploy'

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build:preview

      - name: 'Deploy'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: preview
